resolver: lts-18.13
compiler: ghc-8.10.7
allow-newer: true

packages:
- '.'

extra-deps:
- clock-0.7.2

# Allow users who don't own the .stack dir to use stack. (This is important for
# running on ieng6)
allow-different-user: true

